"""
Detection signals for Provenance Guard.

Signal 1 — LLM Classifier (Groq)
    Sends text to llama-3.3-70b-versatile with a structured prompt.
    Returns a float 0.0–1.0 (1.0 = very likely AI-generated).

Signal 2 — Stylometric Heuristics (pure Python)
    Computes three statistical properties of the text:
      - Sentence length variance  (low variance → more AI-like)
      - Type-token ratio           (low diversity → more AI-like)
      - Punctuation density        (low density → more AI-like)
    Each sub-metric is normalized and combined into a single score.
    Returns a float 0.0–1.0 (1.0 = very uniform / AI-like patterns).
"""

import json
import math
import re
import string
import os

from groq import Groq

_groq_client = None


def _get_groq_client() -> Groq:
    global _groq_client
    if _groq_client is None:
        _groq_client = Groq(api_key=os.environ["GROQ_API_KEY"])
    return _groq_client


# ---------------------------------------------------------------------------
# Signal 1 — LLM Classifier
# ---------------------------------------------------------------------------

_LLM_SYSTEM_PROMPT = """You are an expert forensic linguist specializing in distinguishing
human-written text from AI-generated text. Analyze the provided text and assess the
probability that it was generated by an AI language model.

Consider these indicators of AI-generated text:
- Overly structured, formulaic sentence patterns
- Hedging phrases like "it is important to note", "furthermore", "in conclusion"
- Lack of personal voice, idiosyncrasies, or emotional texture
- Suspiciously even register across the entire passage
- Generic examples that could apply to any context
- Absence of typos, casual phrasing, or stream-of-consciousness markers

Respond ONLY with valid JSON in this exact format:
{"ai_probability": 0.XX, "reasoning": "brief explanation"}

The ai_probability must be a float between 0.0 and 1.0.
0.0 = definitely human-written
1.0 = definitely AI-generated"""


def classify_with_llm(text: str) -> tuple[float, str]:
    """
    Ask Groq to rate the probability that `text` is AI-generated.

    Returns:
        (ai_probability: float, reasoning: str)
    """
    client = _get_groq_client()
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "system", "content": _LLM_SYSTEM_PROMPT},
            {"role": "user", "content": f"Analyze this text:\n\n{text}"},
        ],
        temperature=0.1,  # low temp for consistent scoring
        max_tokens=200,
    )

    raw = response.choices[0].message.content.strip()

    # Extract JSON even if the model wraps it in markdown
    json_match = re.search(r"\{.*\}", raw, re.DOTALL)
    if not json_match:
        # Fallback: if the model misbehaves, return uncertain
        return 0.5, "Could not parse model response"

    data = json.loads(json_match.group())
    probability = float(data.get("ai_probability", 0.5))
    # Clamp to [0, 1] in case the model returns something unexpected
    probability = max(0.0, min(1.0, probability))
    reasoning = data.get("reasoning", "")
    return probability, reasoning


# ---------------------------------------------------------------------------
# Signal 2 — Stylometric Heuristics
# ---------------------------------------------------------------------------

def _split_sentences(text: str) -> list[str]:
    """Split text into sentences using simple punctuation rules."""
    # Split on . ! ? followed by whitespace or end of string
    sentences = re.split(r"(?<=[.!?])\s+", text.strip())
    return [s for s in sentences if len(s.split()) >= 2]


def _sentence_length_variance(sentences: list[str]) -> float:
    """
    Compute standard deviation of word counts per sentence.

    AI text → low variance (sentences cluster around a uniform length).
    Human text → higher variance (mix of short punchy and long complex sentences).

    Returns a score 0.0–1.0 where 1.0 = very low variance (AI-like).
    We invert the normalized std-dev so higher = more AI-like.
    """
    if len(sentences) < 2:
        return 0.5  # not enough data to judge

    lengths = [len(s.split()) for s in sentences]
    mean = sum(lengths) / len(lengths)
    variance = sum((l - mean) ** 2 for l in lengths) / len(lengths)
    std_dev = math.sqrt(variance)

    # Normalize: typical human text has std_dev ~ 5–15 words.
    # We cap at 20 so the score doesn't go negative.
    normalized_std = min(std_dev / 20.0, 1.0)

    # Invert: low std_dev (uniform) → high score (AI-like)
    return 1.0 - normalized_std


def _type_token_ratio(text: str) -> float:
    """
    Type-token ratio (TTR) = unique words / total words.

    AI text → lower TTR (vocabulary repeats more).
    Human text → higher TTR (more diverse vocabulary).

    Returns a score 0.0–1.0 where 1.0 = low diversity (AI-like).
    """
    words = re.findall(r"\b[a-zA-Z]+\b", text.lower())
    if len(words) < 10:
        return 0.5  # too short to judge

    ttr = len(set(words)) / len(words)

    # TTR decreases naturally as text length grows (the "type-token curve").
    # For short texts (< 200 words) it tends to be 0.6–0.9.
    # For longer texts it drops toward 0.4–0.6.
    # We score low TTR as AI-like (high score).
    # Normalize so ttr=0.3 → score≈1.0 and ttr=0.9 → score≈0.0
    score = 1.0 - ((ttr - 0.3) / 0.6)
    return max(0.0, min(1.0, score))


def _punctuation_density(text: str) -> float:
    """
    Punctuation density = punctuation characters / total characters.

    AI text → lower density (clean, sparse punctuation).
    Human text → higher density (dashes, ellipses, exclamation points, quotes).

    Returns a score 0.0–1.0 where 1.0 = low punctuation density (AI-like).
    """
    if not text:
        return 0.5

    punct_chars = sum(1 for c in text if c in string.punctuation)
    density = punct_chars / len(text)

    # Typical human prose: density ~ 0.04–0.12
    # Typical AI prose: density ~ 0.02–0.06
    # Score: low density → high AI score
    # Normalize so density=0.01 → score≈1.0, density=0.12 → score≈0.0
    score = 1.0 - ((density - 0.01) / 0.11)
    return max(0.0, min(1.0, score))


def compute_stylometric_score(text: str) -> dict:
    """
    Combine the three stylometric sub-signals into a single AI probability score.

    Weights:
      - Sentence length variance: 40%  (most reliable signal)
      - Type-token ratio:         35%  (strong but length-dependent)
      - Punctuation density:      25%  (weakest, but independent)

    Returns a dict with:
      style_score: float 0.0–1.0 (1.0 = AI-like)
      sub_scores:  individual scores for transparency
    """
    sentences = _split_sentences(text)

    slv_score = _sentence_length_variance(sentences)
    ttr_score = _type_token_ratio(text)
    pd_score = _punctuation_density(text)

    combined = (0.40 * slv_score) + (0.35 * ttr_score) + (0.25 * pd_score)

    return {
        "style_score": round(combined, 4),
        "sub_scores": {
            "sentence_length_variance": round(slv_score, 4),
            "type_token_ratio": round(ttr_score, 4),
            "punctuation_density": round(pd_score, 4),
        },
    }


# ---------------------------------------------------------------------------
# Confidence Scorer
# ---------------------------------------------------------------------------

def combine_scores(llm_score: float, style_score: float) -> float:
    """
    Weighted average of the two signal scores.

    LLM gets 60% weight: it captures semantic nuance that heuristics miss.
    Stylometric gets 40% weight: fast, interpretable, independent of the LLM.

    Returns a float 0.0–1.0 (1.0 = high confidence of AI generation).
    """
    confidence = (0.60 * llm_score) + (0.40 * style_score)
    return round(confidence, 4)


def get_attribution(confidence: float) -> str:
    """Map a confidence score to an attribution code."""
    if confidence >= 0.70:
        return "likely_ai"
    if confidence >= 0.30:
        return "uncertain"
    return "likely_human"
